[tool.poetry]
name = "myhome"
version = "0.1.0"
description = "Python client library for interacting with Bticino MMYHOMESERVER1"
authors = ["Stephan Peijnik-Steinwender <speijnik@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.0"
click = "^7.1.2"
upnpclient = {version = "^1.0.3", extras = ["autodiscovery"]}
nulltype = "^2.3.1"
urllib3 = "^1.26.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
